app_name: "Flashy Dashboard API"
# Host MongoDB (published from docker-compose "mongo" service)
MONGO_URI: "mongodb://192.168.1.36:27017"
mongo_db_name: "flashy_dashboard"

jwt_secret_key: "CHANGE_ME_IN_PRODUCTION"
jwt_algorithm: "HS256"
access_token_expires_minutes: 1440

app_timezone: "Asia/Bangkok"

