app_name: "Flashy Dashboard API"
mongo_uri: "mongodb://localhost:27017"
mongo_db_name: "flashy_dashboard"

jwt_secret_key: "CHANGE_ME_IN_PRODUCTION"
jwt_algorithm: "HS256"
access_token_expires_minutes: 1440

